-- MySQL Script generated by MySQL Workbench
-- Sat Aug  3 23:01:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(13) NOT NULL,
  `curso` VARCHAR(45) NULL,
  `instituicao_ensino` VARCHAR(45) NULL,
  `senha` VARCHAR(32) NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`id`, `curso`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `curso_UNIQUE` (`curso` ASC) VISIBLE,
  UNIQUE INDEX `senha_UNIQUE` (`senha` ASC) VISIBLE,
  INDEX `fk_autores_cursos1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_autores_cursos1`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resumos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `palavras_chave` VARCHAR(50) NOT NULL,
  `texto` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(32) NULL,
  `curso` INT NOT NULL,
  `formacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliadores_cursos1_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_avaliadores_cursos1`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autorias` (
  `autor` INT NOT NULL,
  `resumo` INT NOT NULL,
  PRIMARY KEY (`autor`, `resumo`),
  INDEX `fk_AUTORES_has_RESUMOS_RESUMOS1_idx` (`resumo` ASC) VISIBLE,
  INDEX `fk_AUTORES_has_RESUMOS_AUTORES1_idx` (`autor` ASC) VISIBLE,
  CONSTRAINT `fk_AUTORES_has_RESUMOS_AUTORES1`
    FOREIGN KEY (`autor`)
    REFERENCES `mydb`.`autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTORES_has_RESUMOS_RESUMOS1`
    FOREIGN KEY (`resumo`)
    REFERENCES `mydb`.`resumos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avaliacoes` (
  `avaliador` INT NOT NULL,
  `resumo` INT NOT NULL,
  `nota` DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (`avaliador`, `resumo`),
  INDEX `fk_avaliadores_has_resumos_resumos1_idx` (`resumo` ASC) VISIBLE,
  INDEX `fk_avaliadores_has_resumos_avaliadores1_idx` (`avaliador` ASC) VISIBLE,
  CONSTRAINT `fk_avaliadores_has_resumos_avaliadores1`
    FOREIGN KEY (`avaliador`)
    REFERENCES `mydb`.`avaliadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliadores_has_resumos_resumos1`
    FOREIGN KEY (`resumo`)
    REFERENCES `mydb`.`resumos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
